version: "2"

run:
  timeout: 3m

linters:
  default: all
  disable:
    - cyclop
    - dupl
    - exhaustive
    - exhaustruct
    - forbidigo
    - err113
    - lll
    - mnd
    - nlreturn
    - noctx
    - paralleltest
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - depguard

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 12
    goconst:
      min-len: 5
      min-occurrences: 4
    misspell:
      locale: US
    funlen:
      lines: -1
      statements: 50
    godox:
      keywords:
        - FIXME
    gofumpt:
      extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
